FROM node:20-alpine AS base

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY nx.json ./

RUN npm ci

COPY libs ./libs
COPY apps/rag-service ./apps/rag-service

EXPOSE 3003

CMD ["npm", "run", "dev:rag"]

