FROM node:20-alpine AS base

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY nx.json ./

RUN npm ci

COPY libs ./libs
COPY apps/api-gateway ./apps/api-gateway

EXPOSE 3000

CMD ["npm", "run", "dev:gateway"]

